// Package pipeline runs a user-defined sequence of text.generate steps: each
// step is a prompt (which may reference {{topic}} and the output of any earlier
// step via {{step-id}}), executed through the provider Resolver with the same
// content-addressed cache as the demo. This is what lets the Studio compose
// arbitrary pipelines instead of only the fixed mini-lesson.
//
// Like the demo, these steps are probabilistic and are not replay-verified
// against a model — they live outside the deterministic kernel by design (see
// docs/adr/0005).
package pipeline

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/lanroo/rexo/internal/providers"
)

// Step is one stage of a pipeline.
type Step struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	System string `json:"system"`
	Prompt string `json:"prompt"`
}

// StepResult is the outcome of one step, with Economy-Engine provenance.
type StepResult struct {
	ID         string
	Title      string
	Provider   string
	Model      string
	CacheHit   bool
	DurationMS int64
	Text       string
}

// Result is the finished pipeline plus per-step provenance.
type Result struct {
	Topic       string
	OutputPath  string
	Steps       []StepResult
	FullyCached bool
}

// Options configures a run.
type Options struct {
	Topic      string
	Lang       string
	Provider   string
	Model      string
	ProjectDir string
	Steps      []Step
	Progress   func(StepResult)
}

const concise = " Be concise and direct. Output only what is asked — no preamble, no meta-commentary, and no explanation of your reasoning."

// Run executes the steps in order, streaming each result through Progress.
func Run(ctx context.Context, opt Options) (*Result, error) {
	topic := strings.TrimSpace(opt.Topic)
	if topic == "" {
		return nil, fmt.Errorf("a goal is required")
	}
	if len(opt.Steps) == 0 {
		return nil, fmt.Errorf("the pipeline has no steps")
	}
	if strings.TrimSpace(opt.Model) != "" {
		os.Setenv("REXO_OLLAMA_MODEL", opt.Model)
	}

	resolver := providers.DefaultResolver(opt.ProjectDir, opt.Provider)
	if len(resolver.Available()) == 0 {
		return nil, fmt.Errorf("no AI provider found — install Claude Code, Codex, or Ollama, then run `rexo doctor`")
	}

	outputs := make(map[string]string, len(opt.Steps))
	lang := languageDirective(opt.Lang)
	result := &Result{Topic: topic, FullyCached: true}

	for i, st := range opt.Steps {
		id := strings.TrimSpace(st.ID)
		if id == "" {
			id = fmt.Sprintf("step%d", i+1)
		}
		system := strings.TrimSpace(st.System)
		if system == "" {
			system = "You are a helpful, expert assistant."
		}
		prompt := strings.TrimSpace(expand(st.Prompt, topic, outputs))
		if prompt == "" {
			return result, fmt.Errorf("step %q has an empty prompt", id)
		}

		req := providers.Request{System: system + lang + concise, Prompt: prompt}
		out, res, err := resolver.Generate(ctx, req)
		if err != nil {
			return result, fmt.Errorf("step %q: %w", id, err)
		}
		outputs[id] = out.Text
		if !res.CacheHit {
			result.FullyCached = false
		}
		sr := StepResult{
			ID:         id,
			Title:      firstNonEmpty(st.Title, id),
			Provider:   res.Provider,
			Model:      out.ModelID,
			CacheHit:   res.CacheHit,
			DurationMS: res.DurationMS,
			Text:       out.Text,
		}
		result.Steps = append(result.Steps, sr)
		if opt.Progress != nil {
			opt.Progress(sr)
		}
	}

	path, err := writeDoc(opt.ProjectDir, topic, result.Steps)
	if err != nil {
		return result, err
	}
	result.OutputPath = path
	return result, nil
}

// expand replaces {{topic}} and each {{step-id}} with the corresponding text.
func expand(tmpl, topic string, outputs map[string]string) string {
	s := strings.ReplaceAll(tmpl, "{{topic}}", topic)
	for id, out := range outputs {
		s = strings.ReplaceAll(s, "{{"+id+"}}", out)
	}
	return s
}

func writeDoc(projectDir, topic string, steps []StepResult) (string, error) {
	dir := filepath.Join(projectDir, ".rexo", "studio")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create output dir: %w", err)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", topic)
	provider := "unknown"
	if len(steps) > 0 {
		provider = steps[0].Provider
	}
	fmt.Fprintf(&b, "_Generated by REXO Studio — capability `text.generate@1`, provider `%s`._\n\n", provider)
	for _, s := range steps {
		fmt.Fprintf(&b, "## %s\n\n%s\n\n", s.Title, strings.TrimSpace(s.Text))
	}
	path := filepath.Join(dir, slug(topic)+".md")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("write output: %w", err)
	}
	return path, nil
}

func languageDirective(lang string) string {
	return " Write your entire response in " + languageName(lang) + "."
}

func languageName(lang string) string {
	switch strings.ToLower(strings.TrimSpace(lang)) {
	case "", "en", "en-us", "english":
		return "English"
	case "pt", "pt-br", "portuguese", "português":
		return "Portuguese"
	case "es", "spanish", "español":
		return "Spanish"
	case "fr", "french", "français":
		return "French"
	default:
		return lang
	}
}

func firstNonEmpty(a, b string) string {
	if strings.TrimSpace(a) != "" {
		return a
	}
	return b
}

func slug(topic string) string {
	var b strings.Builder
	prevDash := false
	for _, r := range strings.ToLower(topic) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			prevDash = false
		default:
			if !prevDash {
				b.WriteByte('-')
				prevDash = true
			}
		}
	}
	s := strings.Trim(b.String(), "-")
	if s == "" {
		s = "output"
	}
	if len(s) > 60 {
		s = strings.Trim(s[:60], "-")
	}
	return s
}
